spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/leavemanagementDB
    username: postgres
    password: 30496039
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always



server:
  port: 8080

jwt:
  key: thisisacodingjustasdemonstrationforsecretkeyinspringsecurityjsonwebtokenauthentication