spring:
  datasource:
    url: jdbc:postgresql://db:5432/leave_management_system_db
    username: leave_management_system_user
    password: leave_management_system_password

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 8080

jwt:
  key: thisisacodingjustasdemonstrationforsecretkeyinspringsecurityjsonwebtokenauthentication
